"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 00:58:44.812172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('elderly_mode', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('answered_by_ai', sa.Integer(), nullable=True),
    sa.Column('handed_to_staff', sa.Integer(), nullable=True),
    sa.Column('account_query', sa.Integer(), nullable=True),
    sa.Column('level_change', sa.String(), nullable=True),
    sa.Column('unanswered_text', sa.Text(), nullable=True),
    sa.Column('assets_json', sa.Text(), nullable=True),
    sa.Column('matched_json', sa.Text(), nullable=True),
    sa.Column('estimated_amount_inr', sa.Integer(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interaction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_events_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_events_session_id'), ['session_id'], unique=False)

    op.create_table('job_locks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('queue_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_tokens_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_tokens_token'), ['token'], unique=False)

    op.create_table('scheme_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('scheme_id', sa.String(), nullable=True),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_age', sa.Integer(), nullable=True),
    sa.Column('customer_branch', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('staff_checks_json', sa.Text(), nullable=True),
    sa.Column('message_local', sa.Text(), nullable=True),
    sa.Column('message_english', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('handled_by', sa.String(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'customer_id', name='uq_alert_scheme_customer')
    )
    with op.batch_alter_table('scheme_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_alerts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheme_alerts_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheme_alerts_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheme_alerts_status'), ['status'], unique=False)

    op.create_table('scheme_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('published_on', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('draft_json', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('validation_issues', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheme_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_drafts_feed_id'), ['feed_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scheme_drafts_status'), ['status'], unique=False)

    op.create_table('scheme_update_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=True),
    sa.Column('new_drafts', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_salt', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_google_sub'), ['google_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_username'), ['username'], unique=True)

    op.create_table('turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('text_local', sa.Text(), nullable=True),
    sa.Column('text_english', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_session_id'))

    op.drop_table('turns')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_username'))
        batch_op.drop_index(batch_op.f('ix_staff_google_sub'))
        batch_op.drop_index(batch_op.f('ix_staff_email'))

    op.drop_table('staff')
    op.drop_table('scheme_update_runs')
    with op.batch_alter_table('scheme_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_scheme_drafts_feed_id'))

    op.drop_table('scheme_drafts')
    with op.batch_alter_table('scheme_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_scheme_alerts_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_scheme_alerts_draft_id'))
        batch_op.drop_index(batch_op.f('ix_scheme_alerts_customer_id'))

    op.drop_table('scheme_alerts')
    with op.batch_alter_table('queue_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_queue_tokens_status'))
        batch_op.drop_index(batch_op.f('ix_queue_tokens_created_at'))

    op.drop_table('queue_tokens')
    op.drop_table('job_locks')
    with op.batch_alter_table('interaction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_interaction_events_kind'))
        batch_op.drop_index(batch_op.f('ix_interaction_events_is_demo'))
        batch_op.drop_index(batch_op.f('ix_interaction_events_created_at'))

    op.drop_table('interaction_events')
    # ### end Alembic commands ###
